resnet: # 50 100 152
    depth: 152
    image_size: 112 
    drop_ratio: 0.4
    net_mode: ir_se # ir ir_se
    feat_dim: 512

efficientnet:
    image_size: 112 
    # about [width, depth, image_size, drop_ratio] see 473-Line in backbone/EfficientNets.py
    width: 1.0
    depth: 1.0
    drop_ratio: 0.2
    # [out_h, out_w] decide the last linear layer, see 835-Line in backbone/EfficientNets.py
    out_h: 7
    out_w: 7
    # feat_dim decide the embedding dim
    feat_dim: 512

swintransformer: # tiny small base
    model_size: base
    image_size: 224
    in_chans: 3
    feat_dim: 512

convnext: # tiny small base large
    model_size: tiny
    feat_dim: 512
    image_size: 224