arcface:
    feat_dim: 512
    num_class: 72778
    margin_arc: 0.35
    margin_am: 0.0
    scale: 32

magface:
    feat_dim: 512
    num_class: 72778
    margin_am: 0.0
    scale: 64
    l_a: 10
    u_a: 110
    l_margin: 0.45
    u_margin: 0.8
    lamda: 20

circle:
    feat_dim: 512
    num_class: 72778
    margin: 0.25
    gamma: 256

mv-softmax:
    feat_dim: 512
    num_class: 72778
    is_am: 1
    margin: 0.35
    mv_weight: 1.12
    scale: 32