model:
  task: classification
  name: torchvision-swin_b
  image_size: &resize_size 224
  kwargs: {} # kwargs feed into torchvision-style models.__init__ 'attention_dropout': 0.1,
  num_classes: 35
  pretrained: True
  backbone_freeze: False
  bn_freeze: False
  bn_freeze_affine: False
  attention_pool: False
data:
  root: wuji3/oxford-iiit-pet
  nw: 64 # if not multi-nw, set to 0
  train:
    bs: 320 # per gpu
    base_aug: null
    class_aug: null
      # Abyssinian: [1,2,3,4]
      # Birman: [1,2,3,4]
    augment: # refer to utils/augment.py
       - random_choice:
          transforms: 
            - random_color_jitter:
                brightness: 0.1
                contrast: 0.1
                saturation: 0.1
                hue: 0.1
            - random_cutout:
                n_holes: 3
                length: 12
                prob: 0.1
                color: [0, 255]
            - random_gaussianblur:
                kernel_size: 5
            - random_rotate:
                degrees: 10
            - random_autocontrast:
                p: 0.5
            - random_adjustsharpness:
                p: 0.5
            - random_augmix: 
                severity: 3
       - random_horizonflip: 
           p: 0.5
       - random_choice:
          transforms:
            - resize_and_padding: 
                size: *resize_size
                training: True
            - random_crop_and_resize:
                size: *resize_size
                scale: [0.7, 1]
          p: [0.9, 0.1]
       - to_tensor: no_params
       - normalize: 
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
    aug_epoch: 13 
  val:
    bs: 320
    augment:
        - resize_and_padding:
            size: *resize_size
            training: False
        - to_tensor: no_params
        - normalize: 
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
hyp:
  epochs: 15
  lr0: 0.06 
  lrf_ratio: null # decay to lrf_ratio * lr0, if None, 0.1
  momentum: 0.937
  weight_decay: 0.0005
  warmup_momentum: 0.8
  warm_ep: 1
  loss:
    ce: True
    bce:
      - False
      - 0.5
      - False # multi-label
  label_smooth: 0.1
  strategy:
    prog_learn: False
    mixup:
      ratio: 0.0
      duration: 10
    focal: 
      - False
      - 0.25
      - 1.5
    ohem:
      - False
      - 8 # min_kept
      - 0.7 # thresh_prob
      - 255 # ignore_index
  optimizer: 
    - sgd # sgd, adam or sam
    - False # Different layers in the model set different learning rates, in built/layer_optimizer
  scheduler: cosine_with_warm # linear or cosine