resnet:
    depth: 152
    drop_ratio: 0.4
    net_mode: ir_se
    feat_dim: 512
    out_h: 7
    out_w: 7

efficientnet:
    width: 1.0
    depth: 1.0
    image_size: 112
    drop_ratio: 0.2
    out_h: 7
    out_w: 7
    feat_dim: 512

swintransformer:
    img_size: 224
    patch_size: 4
    in_chans: 3
    embed_dim: 96
    depths:
    - 2
    - 2
    - 18
    - 2
    num_heads:
    - 3
    - 6
    - 12
    - 24
    window_size: 7
    mlp_ratio: 4.0
    drop_rate: 0.0
    drop_path_rate: 0.3
