model:
  task: cbir
  backbone:
    efficientnet: # about [width, depth, image_size, drop_ratio] see 473-Line in backbone/EfficientNets.py
      image_size: 224
      width: 1.0
      depth: 1.0
      drop_ratio: 0.2
      # feat_dim decide the embedding dim
      feat_dim: 512
  head:
    arcface:
      feat_dim: 512
      num_class: 640
      margin_arc: 0.35
      margin_am: 0.0
      scale: 32
data:
  root: /home/duke/visiondk/data/favie/v1-pipeline  # -train -val
  nw: 16 # if not multi-nw, set to 0
  train:
    bs: 160 # one gpus if DDP
    common_aug: null 
    class_aug: null
      #S: 0 1 2 4 5 6
      #B-: 0 1 2 4 5 6
    augment: # refer to utils/augment.py
      random_cutout:
        n_holes: 3
        length: 24
        prob: 0.2
        color: [0, 255]
      random_choice:
      - random_gaussianblur:
          kernel_size: 5
      #random_localgaussian:
      #  ksize: [17, 17]
      - random_rotate:
          degrees: 20
      - random_horizonflip:
          p: 0.5
      - random_autocontrast:
          p: 0.5
      - random_adjustsharpness:
          p: 0.5
      pad2square: no_params
      resize:
        size: 224
      to_tensor: no_params
      normalize: # default use ImageNet1K mean & var, if not pretrained, del normalize 
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    aug_epoch: 25 # augment for epochs, on which epoch to weaken, except warm_epoch
  val:
    bs: 32
    metrics:
      metrics: [mrr, recall, precision, auc, ndcg]
      cutoffs: [1, 3, 5] 
    augment:
        pad2square: no_params
        resize:
          size: 224
        to_tensor: no_params
        normalize: # default use ImageNet1K mean & var, if not pretrained, del normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
hyp:
  epochs: 30
  lr0: 0.1 # sgd=1e-2, adam=1e-3
  lrf_ratio: null # decay to lrf_ratio * lr0, if None, 0.1
  momentum: 0.937
  weight_decay: 0.0005
  warmup_momentum: 0.8
  warm_ep: 2
  loss:
    ce: True
  label_smooth: 0.0
  optimizer: 
    - sgd # sgd, adam or sam
    - False # Different layers in the model set different learning rates, in built/layer_optimizer
  scheduler: cosine_with_warm # linear or cosine
