model:
  choice: torchvision-resnext50_32x4d # torchvision- or custom-
  num_classes: 6 # out_channels of fc, maybe be not equal to num_classes of train_dir. eg: maybe more than num_classes
  pretrained: True
  backbone_freeze: False
  bn_freeze: False
  bn_freeze_affine: False
data:
  root: ./data # -train -val
  nw: 4 # if not multi-nw, set to 0
  train:
    bs: 8 # all gpus if DDP
    augment: # refer to utils/augment.py
      color_jitter
      random_cutout
      random_horizonflip
      to_tensor
      normalize # default use ImageNet1K mean & var, if not pretrained, del normalize
    aug_epoch: 25 # augment for epochs, on which epoch to weaken, except warm_epoch
  val:
    bs: 8
    augment:
      to_tensor
      normalize
hyp:
  epochs: 40
  lr0: 0.01 # sgd=1e-2, adam=1e-3
  lrf_ratio: None # decay to lrf_ratio * lr0, if None, 0.1
  momentum: 0.937
  weight_decay: 0.0005
  warmup_momentum: 0.8
  warm_ep: 2 # out of epochs, imp linear
  loss:
    ce: False
    bce: True
  label_smooth: 0.1
  strategy:
    mixup: 0.2 25 # ratio and mixup_epoch, on which epoch to delete mixup, support ce and bce
    focal: 1 2 # turn-on-or-off and start_epo (except warm_epoch)
  optimizer: sgd # sgd or adam
  scheduler: cosine # linear or cosine